set resource-dir default value to the buildout directory
when resource-dir was not specified in the buildout.cfg, its default value
was set to None, which results in the following exception in ConfigParser:
TypeError: argument of type 'NoneType' is not iterable